// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: pkg/plugin/sdk/authz/authz.proto

package authz

import (
	context "context"
	proto "github.com/gameap/gameap/pkg/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Ability names, e.g. "game-server-start" or "plugin:<id>:<name>".
	Abilities []string `protobuf:"bytes,2,rep,name=abilities,proto3" json:"abilities,omitempty"`
}

func (x *CanRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CanRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CanRequest) GetAbilities() []string {
	if x != nil {
		return x.Abilities
	}
	return nil
}

type CanForEntityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     uint64           `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EntityType proto.EntityType `protobuf:"varint,2,opt,name=entity_type,json=entityType,proto3,enum=gameap.EntityType" json:"entity_type,omitempty"`
	EntityId   uint64           `protobuf:"varint,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Abilities  []string         `protobuf:"bytes,4,rep,name=abilities,proto3" json:"abilities,omitempty"`
}

func (x *CanForEntityRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CanForEntityRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CanForEntityRequest) GetEntityType() proto.EntityType {
	if x != nil {
		return x.EntityType
	}
	return proto.EntityType_ENTITY_TYPE_UNSPECIFIED
}

func (x *CanForEntityRequest) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *CanForEntityRequest) GetAbilities() []string {
	if x != nil {
		return x.Abilities
	}
	return nil
}

type CanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// Set when the check could not be performed; allowed is false in that case
	// and must not be read as a denial decision.
	Error *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *CanResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CanResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CanResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type GetUserRolesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserRolesRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetUserRolesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserRolesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []string `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Error *string  `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *GetUserRolesResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetUserRolesResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetUserRolesResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// AuthzService provides read-only permission checks to plugins.
// Available to every plugin: answering "may this user do X" never changes
// state. Managing roles and permissions lives in the gameap-rbac module,
// which requires the "manage_rbac" plugin permission.
//
// Every method reports failures through the response `error` field and never
// returns an error to the host: a host-side error traps the guest call.
//
// go:plugin type=host module=gameap-authz
type AuthzService interface {
	// Can reports whether the user holds ALL of the listed abilities globally.
	Can(context.Context, *CanRequest) (*CanResponse, error)
	// CanOneOf reports whether the user holds AT LEAST ONE of the listed
	// abilities globally.
	CanOneOf(context.Context, *CanRequest) (*CanResponse, error)
	// CanForEntity reports whether the user holds ALL of the listed abilities
	// for the given entity.
	CanForEntity(context.Context, *CanForEntityRequest) (*CanResponse, error)
	// CanAnyForEntity reports whether the user holds AT LEAST ONE of the listed
	// abilities for the given entity.
	CanAnyForEntity(context.Context, *CanForEntityRequest) (*CanResponse, error)
	// GetUserRoles returns the names of the roles assigned to the user.
	GetUserRoles(context.Context, *GetUserRolesRequest) (*GetUserRolesResponse, error)
}
