version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - err113
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - forbidigo
    - funlen
    #- forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - iface
    - importas
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - modernize
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unqueryvet
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    # - wrapcheck
  settings:
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: lax
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
          deny:
            - pkg: io/ioutil
              desc: 'replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil'
    funlen:
      lines: 100
      statements: 60
    goconst:
      ignore-string-values:
        - "localhost"
        - "email"
        - "name"
        - "server_id"
        - "created_at"
        - "updated_at"
        - "mysql"
    loggercheck:
      slog: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go|test
        linters:
          - depguard
          - dupl
          - funlen
          - gocognit
          - gosec
          - godox
          - govet
          - lll
          - noctx
          - scopelint
      - path: migrations/
        linters:
          - err113
          - funlen
          - lll
          - revive
      - path: internal/api/router\.go
        linters:
          - revive
        text: var-naming
      - path: pkg/api/
        linters:
          - revive
        text: var-naming
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
