import type { PluginDefinition } from '@gameap/plugin-sdk';
import PluginPage from './components/PluginPage.vue';
import DashboardWidget from './components/DashboardWidget.vue';
import ServerTab from './components/ServerTab.vue';

export const serverLoggerPlugin: PluginDefinition = {
    id: 'fwgfo26jzwnm4',
    name: 'Server Logger',
    version: '1.0.0',
    apiVersion: '1.0',
    description: 'Logs server lifecycle events and provides statistics',
    author: 'GameAP',

    translations: {
        en: {
            'title': 'Server Logger',
            'description': 'This plugin logs server lifecycle events and provides statistics.',
            'plugin_status': 'Plugin Status',
            'statistics': 'Statistics',
            'current_user': 'Current User',
            'about': 'About',
            'loading_status': 'Loading status...',
            'loading_stats': 'Loading stats...',
            'status': 'Status',
            'plugin': 'Plugin',
            'version': 'Version',
            'events_processed': 'Events Processed',
            'requested_by': 'Requested by',
            'logged_in_as': 'Logged in as',
            'roles': 'Roles',
            'admin': 'Admin',
            'yes': 'Yes',
            'no': 'No',
            'none': 'None',
            'refresh_all': 'Refresh All',
            'about_text': 'The Server Logger plugin subscribes to all server lifecycle events (start, stop, restart, install, update, reinstall, delete) and logs them. It demonstrates how to:',
            'feature_events': 'Subscribe to server events',
            'feature_game_info': 'Access game and gamemod information',
            'feature_http_api': 'Create HTTP API endpoints',
            'feature_frontend': 'Build a frontend with Vue components',
            'menu_item': 'Server Logger',
            'server_tab': 'Logger',
            'dashboard_widget': 'Server Logger Stats',
            'refresh': 'Refresh',
            'server_logger_info': 'Server Logger Info',
            'loading_server_info': 'Loading server info from plugin...',
            'server_id': 'Server ID',
            'server_name': 'Server Name',
            'ip_address': 'IP Address',
            'port': 'Port',
            'server_data_props': 'Server Data from Props',
            'name': 'Name',
            'game': 'Game',
            'address': 'Address',
            'status_running': 'Running',
            'status_disabled': 'Disabled',
            'status_stopped': 'Stopped',
            'status_unknown': 'Unknown',
            'na': 'N/A',
        },
        ru: {
            'title': 'Логгер серверов',
            'description': 'Этот плагин логирует события жизненного цикла серверов и предоставляет статистику.',
            'plugin_status': 'Статус плагина',
            'statistics': 'Статистика',
            'current_user': 'Текущий пользователь',
            'about': 'О плагине',
            'loading_status': 'Загрузка статуса...',
            'loading_stats': 'Загрузка статистики...',
            'status': 'Статус',
            'plugin': 'Плагин',
            'version': 'Версия',
            'events_processed': 'Обработано событий',
            'requested_by': 'Запрошено',
            'logged_in_as': 'Вы вошли как',
            'roles': 'Роли',
            'admin': 'Администратор',
            'yes': 'Да',
            'no': 'Нет',
            'none': 'Нет',
            'refresh_all': 'Обновить всё',
            'about_text': 'Плагин Server Logger подписывается на все события жизненного цикла серверов (запуск, остановка, перезапуск, установка, обновление, переустановка, удаление) и логирует их. Он демонстрирует:',
            'feature_events': 'Подписку на события сервера',
            'feature_game_info': 'Доступ к информации об игре и модификации',
            'feature_http_api': 'Создание HTTP API эндпоинтов',
            'feature_frontend': 'Создание фронтенда с Vue компонентами',
            'menu_item': 'Логгер серверов',
            'server_tab': 'Логгер',
            'dashboard_widget': 'Статистика логгера',
            'refresh': 'Обновить',
            'server_logger_info': 'Информация логгера',
            'loading_server_info': 'Загрузка информации о сервере...',
            'server_id': 'ID сервера',
            'server_name': 'Имя сервера',
            'ip_address': 'IP адрес',
            'port': 'Порт',
            'server_data_props': 'Данные сервера из props',
            'name': 'Имя',
            'game': 'Игра',
            'address': 'Адрес',
            'status_running': 'Запущен',
            'status_disabled': 'Отключён',
            'status_stopped': 'Остановлен',
            'status_unknown': 'Неизвестно',
            'na': 'Н/Д',
        },
    },

    routes: [
        {
            path: '/',
            name: 'index',
            component: PluginPage,
            meta: { title: 'Server Logger' },
        },
    ],

    menuItems: [
        {
            section: 'servers',
            icon: 'fas fa-clipboard-list',
            text: '@:menu_item',
            route: { name: 'index' },
            order: 100,
        },
    ],

    homeButtons: [
        {
            name: '@:title',
            icon: 'fas fa-clipboard-list',
            route: { name: 'index' },
            order: 100,
        },
    ],

    slots: {
        'dashboard-widgets': [
            {
                component: DashboardWidget,
                order: 50,
                label: '@:dashboard_widget',
            },
        ],
        'server-tabs': [
            {
                component: ServerTab,
                order: 100,
                label: '@:server_tab',
                icon: 'fas fa-clipboard-list',
                name: 'logger',
            },
        ],
    },
};
