GET {{host}}/gdaemon_api/servers_tasks
Content-Type: application/json
X-Auth-Token: {{gdaemonAPIToken}}


###

GET http://localhost:2080/gdaemon_api/servers_tasks
Content-Type: application/json
X-Auth-Token: {{gdaemonAPIToken}}