//go:build wasip1

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// Patched: response buffers allocated by the host are freed after unmarshal.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: pkg/plugin/sdk/servers/servers.proto

package servers

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
	_ "unsafe"
)

type serversService struct{}

func NewServersService() ServersService {
	return serversService{}
}

//go:wasmimport gameap-servers find_servers
func _find_servers(ptr uint32, size uint32) uint64

func (h serversService) FindServers(ctx context.Context, request *FindServersRequest) (*FindServersResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _find_servers(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(FindServersResponse)
	err = response.UnmarshalVT(buf)
	if ptr != 0 {
		wasm.Free(ptr)
	}
	if err != nil {
		return nil, err
	}
	return response, nil
}

//go:wasmimport gameap-servers get_server
func _get_server(ptr uint32, size uint32) uint64

func (h serversService) GetServer(ctx context.Context, request *GetServerRequest) (*GetServerResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _get_server(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(GetServerResponse)
	err = response.UnmarshalVT(buf)
	if ptr != 0 {
		wasm.Free(ptr)
	}
	if err != nil {
		return nil, err
	}
	return response, nil
}

//go:wasmimport gameap-servers save_server
func _save_server(ptr uint32, size uint32) uint64

func (h serversService) SaveServer(ctx context.Context, request *SaveServerRequest) (*SaveServerResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _save_server(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(SaveServerResponse)
	err = response.UnmarshalVT(buf)
	if ptr != 0 {
		wasm.Free(ptr)
	}
	if err != nil {
		return nil, err
	}
	return response, nil
}

//go:wasmimport gameap-servers delete_server
func _delete_server(ptr uint32, size uint32) uint64

func (h serversService) DeleteServer(ctx context.Context, request *DeleteServerRequest) (*DeleteServerResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _delete_server(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(DeleteServerResponse)
	err = response.UnmarshalVT(buf)
	if ptr != 0 {
		wasm.Free(ptr)
	}
	if err != nil {
		return nil, err
	}
	return response, nil
}
