// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: pkg/plugin/sdk/protocol/protocol.proto

package protocol

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RconTransport selects how an RCON protocol registration is executed.
type RconTransport int32

const (
	// RCON_TRANSPORT_UNSPECIFIED is not a usable transport — it is the proto3
	// zero value, present only to satisfy the enum-default rule. A registration
	// left at this value still overrides the built-in mapping for its games,
	// but every RCON attempt then fails with "unknown rcon transport" and the
	// features endpoint reports RCON as unsupported. Always set a transport
	// explicitly.
	RconTransport_RCON_TRANSPORT_UNSPECIFIED RconTransport = 0
	// RCON_TRANSPORT_BUILTIN_SOURCE is a shorthand for RCON_TRANSPORT_BUILTIN
	// with builtin_protocol "source", kept for plugins built before that field
	// existed. New plugins should use RCON_TRANSPORT_BUILTIN.
	RconTransport_RCON_TRANSPORT_BUILTIN_SOURCE RconTransport = 1
	// RCON_TRANSPORT_BUILTIN_GOLDSOURCE is a shorthand for
	// RCON_TRANSPORT_BUILTIN with builtin_protocol "goldsource", kept for
	// backward compatibility like the Source variant above.
	RconTransport_RCON_TRANSPORT_BUILTIN_GOLDSOURCE RconTransport = 2
	// RCON_TRANSPORT_PLUGIN means the plugin implements the wire protocol
	// itself through RconOpen / RconExecute / RconClose, doing I/O over the
	// host-opened conn_handle with the gameap-net host library.
	//
	// This requires that library: with PLUGIN_NET_ENABLED=false the host drops
	// such registrations entirely rather than let an unrunnable protocol shadow
	// the built-in tables, so games that also have a built-in mapping keep
	// working while the plugin protocol is simply absent.
	RconTransport_RCON_TRANSPORT_PLUGIN RconTransport = 3
	// RCON_TRANSPORT_BUILTIN reuses one of the panel's own RCON engines, named
	// by RconProtocol.builtin_protocol. Purely declarative: no plugin code runs
	// at execute time, the gameap-net host library is not involved, and the
	// registration keeps working with PLUGIN_NET_ENABLED=false. Use it to teach
	// the panel about a new game that speaks a protocol it already implements.
	//
	// This is the form to prefer: a protocol the panel gains later becomes
	// available to plugins without any change to this enum.
	RconTransport_RCON_TRANSPORT_BUILTIN RconTransport = 4
)

// Enum value maps for RconTransport.
var (
	RconTransport_name = map[int32]string{
		0: "RCON_TRANSPORT_UNSPECIFIED",
		1: "RCON_TRANSPORT_BUILTIN_SOURCE",
		2: "RCON_TRANSPORT_BUILTIN_GOLDSOURCE",
		3: "RCON_TRANSPORT_PLUGIN",
		4: "RCON_TRANSPORT_BUILTIN",
	}
	RconTransport_value = map[string]int32{
		"RCON_TRANSPORT_UNSPECIFIED":        0,
		"RCON_TRANSPORT_BUILTIN_SOURCE":     1,
		"RCON_TRANSPORT_BUILTIN_GOLDSOURCE": 2,
		"RCON_TRANSPORT_PLUGIN":             3,
		"RCON_TRANSPORT_BUILTIN":            4,
	}
)

func (x RconTransport) Enum() *RconTransport {
	p := new(RconTransport)
	*p = x
	return p
}

// QueryTransport selects how a Query protocol registration is executed.
type QueryTransport int32

const (
	// QUERY_TRANSPORT_UNSPECIFIED is not a usable transport — see
	// RCON_TRANSPORT_UNSPECIFIED. A registration left at this value shadows the
	// built-in mapping and then fails every query with "unknown query
	// transport".
	QueryTransport_QUERY_TRANSPORT_UNSPECIFIED QueryTransport = 0
	// QUERY_TRANSPORT_BUILTIN reuses one of the panel's own query engines,
	// named by QueryProtocol.builtin_protocol. Purely declarative: no plugin
	// code runs at query time and the registration works with
	// PLUGIN_NET_ENABLED=false.
	QueryTransport_QUERY_TRANSPORT_BUILTIN QueryTransport = 1
	// QUERY_TRANSPORT_PLUGIN means the plugin implements the query wire
	// protocol in QueryServer, over the UDP conn_handle the host opened for the
	// call. Requires the gameap-net host library; with PLUGIN_NET_ENABLED=false
	// the host drops such registrations, as for RCON_TRANSPORT_PLUGIN.
	QueryTransport_QUERY_TRANSPORT_PLUGIN QueryTransport = 2
)

// Enum value maps for QueryTransport.
var (
	QueryTransport_name = map[int32]string{
		0: "QUERY_TRANSPORT_UNSPECIFIED",
		1: "QUERY_TRANSPORT_BUILTIN",
		2: "QUERY_TRANSPORT_PLUGIN",
	}
	QueryTransport_value = map[string]int32{
		"QUERY_TRANSPORT_UNSPECIFIED": 0,
		"QUERY_TRANSPORT_BUILTIN":     1,
		"QUERY_TRANSPORT_PLUGIN":      2,
	}
)

func (x QueryTransport) Enum() *QueryTransport {
	p := new(QueryTransport)
	*p = x
	return p
}

// PlayerCapability declares player-management support for an RCON protocol:
// listing players, and kicking or banning one of them.
//
// The commands are templates rendered by the host, which substitutes these
// placeholders before sending the result over RCON:
//
//	{id}       player id as reported by the players list
//	{name}     player nickname
//	{uniqid}   stable player identity (SteamID, UUID, …)
//	{ping}     player ping
//	{score}    player score
//	{addr}     player IP address
//	{reason}   kick/ban reason supplied by the panel user (may be empty)
//	{duration} ban duration in whole seconds; 0 for a kick
//
// Values are substituted verbatim, without quoting or escaping, so a template
// must include whatever quoting its console needs. The host does reject any
// request field containing CR, LF, ";" or NUL before rendering, so a panel user
// cannot append a second console command through a reason or a nickname.
//
// A placeholder that names a player identity ({id}, {name} or {uniqid}) must
// resolve to a non-empty value; otherwise the request is rejected before
// anything is sent to the server.
type PlayerCapability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// supported turns player management on. When false the panel reports the
	// feature as unavailable and refuses the players/kick/ban endpoints, even
	// if the command templates below are filled in.
	Supported bool `protobuf:"varint,1,opt,name=supported,proto3" json:"supported,omitempty"`
	// players_command is sent verbatim over RCON to list players (for example
	// "status" or "list uuids"). Its raw output is handed to the parser chosen
	// by parse_via_plugin.
	PlayersCommand string `protobuf:"bytes,2,opt,name=players_command,json=playersCommand,proto3" json:"players_command,omitempty"`
	// kick_command is the template rendered for a kick, for example
	// "kickid {id} {reason}". {duration} renders as 0 here.
	KickCommand string `protobuf:"bytes,3,opt,name=kick_command,json=kickCommand,proto3" json:"kick_command,omitempty"`
	// ban_command is the template rendered for a ban, for example
	// "banid {duration} {uniqid} {reason}".
	BanCommand string `protobuf:"bytes,4,opt,name=ban_command,json=banCommand,proto3" json:"ban_command,omitempty"`
	// parse_via_plugin routes the players_command output to the ParsePlayers
	// RPC. When false the host parses it with the built-in parser selected by
	// game code, and a game with no built-in parser then fails at request time —
	// set this whenever the output is not in a format the panel already knows.
	ParseViaPlugin bool `protobuf:"varint,5,opt,name=parse_via_plugin,json=parseViaPlugin,proto3" json:"parse_via_plugin,omitempty"`
}

func (x *PlayerCapability) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *PlayerCapability) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

func (x *PlayerCapability) GetPlayersCommand() string {
	if x != nil {
		return x.PlayersCommand
	}
	return ""
}

func (x *PlayerCapability) GetKickCommand() string {
	if x != nil {
		return x.KickCommand
	}
	return ""
}

func (x *PlayerCapability) GetBanCommand() string {
	if x != nil {
		return x.BanCommand
	}
	return ""
}

func (x *PlayerCapability) GetParseViaPlugin() bool {
	if x != nil {
		return x.ParseViaPlugin
	}
	return false
}

// RconProtocol registers one RCON protocol: which games it applies to, how it
// is executed, and whether it supports player management.
type RconProtocol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id identifies this protocol within the plugin. The host echoes it back as
	// protocol_id in every execution RPC, so a plugin serving several protocols
	// uses it to tell them apart. Must be unique within the plugin and stable
	// across restarts.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is a human-readable label used for diagnostics only; it plays no
	// part in resolution.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// game_codes lists the panel game codes (the "code" column of the games
	// table, e.g. "cs", "minecraft") this protocol serves. Matched
	// case-insensitively and checked before engines, so a game-code entry beats
	// any engine-level registration.
	GameCodes []string `protobuf:"bytes,3,rep,name=game_codes,json=gameCodes,proto3" json:"game_codes,omitempty"`
	// engines lists the panel game engines (the "engine" column, e.g. "source",
	// "goldsource") this protocol serves. Matched case-insensitively, and only
	// when no registration matched by game code. Use it to claim a whole family
	// of games at once.
	Engines []string `protobuf:"bytes,4,rep,name=engines,proto3" json:"engines,omitempty"`
	// transport picks the execution path; see RconTransport. Always set it
	// explicitly — the unspecified default disables RCON for the claimed games.
	Transport RconTransport `protobuf:"varint,5,opt,name=transport,proto3,enum=gameap.plugin.sdk.protocol.RconTransport" json:"transport,omitempty"`
	// players declares kick/ban/list support. Leave unset (or unsupported) when
	// the protocol only executes raw console commands.
	Players *PlayerCapability `protobuf:"bytes,6,opt,name=players,proto3" json:"players,omitempty"`
	// builtin_protocol names the panel RCON engine to reuse when transport is
	// RCON_TRANSPORT_BUILTIN: one of "source", "goldsource", "quake2",
	// "quake3", "samp", "battleye". An unknown or empty name makes the host drop
	// the whole registration with a warning, so a typo cannot shadow the
	// built-in tables and leave the game without RCON. Ignored for
	// RCON_TRANSPORT_PLUGIN and for the two legacy shorthand transports.
	BuiltinProtocol string `protobuf:"bytes,7,opt,name=builtin_protocol,json=builtinProtocol,proto3" json:"builtin_protocol,omitempty"`
}

func (x *RconProtocol) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RconProtocol) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RconProtocol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RconProtocol) GetGameCodes() []string {
	if x != nil {
		return x.GameCodes
	}
	return nil
}

func (x *RconProtocol) GetEngines() []string {
	if x != nil {
		return x.Engines
	}
	return nil
}

func (x *RconProtocol) GetTransport() RconTransport {
	if x != nil {
		return x.Transport
	}
	return RconTransport_RCON_TRANSPORT_UNSPECIFIED
}

func (x *RconProtocol) GetPlayers() *PlayerCapability {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *RconProtocol) GetBuiltinProtocol() string {
	if x != nil {
		return x.BuiltinProtocol
	}
	return ""
}

// QueryProtocol registers one Query (server status) protocol.
type QueryProtocol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id identifies this protocol within the plugin and is echoed back as
	// protocol_id in QueryServer. Must be unique within the plugin.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is a human-readable label used for diagnostics only.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// engines lists the panel game engines this protocol serves, matched
	// case-insensitively and consulted only when no game_codes matched.
	Engines []string `protobuf:"bytes,3,rep,name=engines,proto3" json:"engines,omitempty"`
	// game_codes lists the panel game codes this protocol serves, matched
	// case-insensitively and checked before engines.
	GameCodes []string `protobuf:"bytes,4,rep,name=game_codes,json=gameCodes,proto3" json:"game_codes,omitempty"`
	// transport picks the execution path; see QueryTransport.
	Transport QueryTransport `protobuf:"varint,5,opt,name=transport,proto3,enum=gameap.plugin.sdk.protocol.QueryTransport" json:"transport,omitempty"`
	// builtin_protocol names the panel query engine to reuse when transport is
	// QUERY_TRANSPORT_BUILTIN: one of "source", "minecraft", "gamespy2",
	// "gamespy3", "quake2", "quake3", "samp", "raknet". An unknown name is
	// reported as an unsupported protocol when the query runs. Ignored for
	// QUERY_TRANSPORT_PLUGIN.
	BuiltinProtocol string `protobuf:"bytes,6,opt,name=builtin_protocol,json=builtinProtocol,proto3" json:"builtin_protocol,omitempty"`
}

func (x *QueryProtocol) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *QueryProtocol) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueryProtocol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryProtocol) GetEngines() []string {
	if x != nil {
		return x.Engines
	}
	return nil
}

func (x *QueryProtocol) GetGameCodes() []string {
	if x != nil {
		return x.GameCodes
	}
	return nil
}

func (x *QueryProtocol) GetTransport() QueryTransport {
	if x != nil {
		return x.Transport
	}
	return QueryTransport_QUERY_TRANSPORT_UNSPECIFIED
}

func (x *QueryProtocol) GetBuiltinProtocol() string {
	if x != nil {
		return x.BuiltinProtocol
	}
	return ""
}

type GetRconProtocolsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRconProtocolsRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

type GetRconProtocolsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// protocols is the plugin's complete RCON registration list. It is read once
	// at load time, so later changes take effect only after a plugin reload.
	Protocols []*RconProtocol `protobuf:"bytes,1,rep,name=protocols,proto3" json:"protocols,omitempty"`
}

func (x *GetRconProtocolsResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetRconProtocolsResponse) GetProtocols() []*RconProtocol {
	if x != nil {
		return x.Protocols
	}
	return nil
}

type GetQueryProtocolsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetQueryProtocolsRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

type GetQueryProtocolsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// protocols is the plugin's complete Query registration list, read once at
	// load time.
	Protocols []*QueryProtocol `protobuf:"bytes,1,rep,name=protocols,proto3" json:"protocols,omitempty"`
}

func (x *GetQueryProtocolsResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetQueryProtocolsResponse) GetProtocols() []*QueryProtocol {
	if x != nil {
		return x.Protocols
	}
	return nil
}

// RconPlayer is one entry of a parsed players list. Every field is a string,
// mirroring the panel's built-in parsers, and unknown fields are left empty
// rather than guessed.
//
// These values travel to the UI and come back in a later kick/ban request,
// where the host rejects CR, LF, ";" and NUL — avoid emitting them, since a
// player whose parsed identity carries one could not be kicked.
type RconPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is the server-assigned player id (Valve userid, slot number, …), used
	// by the {id} template placeholder.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the player nickname, used by {name}.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// ping in milliseconds, used by {ping}. Informational.
	Ping string `protobuf:"bytes,3,opt,name=ping,proto3" json:"ping,omitempty"`
	// score, used by {score}. Informational.
	Score string `protobuf:"bytes,4,opt,name=score,proto3" json:"score,omitempty"`
	// addr is the player IP address without a port, used by {addr}.
	Addr string `protobuf:"bytes,5,opt,name=addr,proto3" json:"addr,omitempty"`
	// uniqid is the stable player identity (SteamID, Minecraft UUID, …), used by
	// {uniqid}. Prefer it for kick/ban templates: unlike id it survives
	// reconnects. When empty the panel falls back to id.
	Uniqid string `protobuf:"bytes,6,opt,name=uniqid,proto3" json:"uniqid,omitempty"`
}

func (x *RconPlayer) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RconPlayer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RconPlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RconPlayer) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

func (x *RconPlayer) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

func (x *RconPlayer) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RconPlayer) GetUniqid() string {
	if x != nil {
		return x.Uniqid
	}
	return ""
}

// RconOpenRequest asks the plugin to authenticate a connection the host has
// already dialled and guarded.
type RconOpenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// protocol_id is the RconProtocol.id this call belongs to.
	ProtocolId string `protobuf:"bytes,1,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	// conn_handle is an opaque, non-zero handle to the connection the host
	// opened to the game server. Pass it to the gameap-net host library to send
	// and receive; the plugin can neither dial nor reach any other target.
	//
	// RCON connections are always TCP — a UDP-based RCON protocol cannot be
	// implemented through this transport, and a game that needs one is better
	// served by a built-in transport.
	//
	// The handle belongs to this plugin, expires after
	// PLUGIN_NET_MAX_TIMEOUT, and counts against the per-plugin open
	// connection cap (PLUGIN_NET_MAX_CONNECTIONS). The same handle is reused by
	// RconExecute and RconClose until the panel closes the client.
	ConnHandle uint64 `protobuf:"varint,2,opt,name=conn_handle,json=connHandle,proto3" json:"conn_handle,omitempty"`
	// password is the server's RCON password from the panel's server record.
	// Treat it as a secret: use it for the handshake, never log or store it.
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// address is the "host:port" the host dialled, for logging and for protocols
	// that mix it into the handshake. Informational — the connection is already
	// established.
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *RconOpenRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RconOpenRequest) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

func (x *RconOpenRequest) GetConnHandle() uint64 {
	if x != nil {
		return x.ConnHandle
	}
	return 0
}

func (x *RconOpenRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RconOpenRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RconOpenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ok reports a successful handshake. When false and auth_failed is not set,
	// the error field explains why.
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// auth_failed marks a rejected password specifically. It is checked before
	// ok and surfaces to the API caller as an authentication failure (HTTP 422)
	// instead of a generic connection error, so set it whenever the server
	// answered but refused the credentials.
	AuthFailed bool `protobuf:"varint,2,opt,name=auth_failed,json=authFailed,proto3" json:"auth_failed,omitempty"`
	// error describes a failure when ok is false. A missing or empty message
	// becomes "plugin rcon open failed". The host closes and releases the
	// connection on any failure, so the handle must not be used afterwards.
	Error *string `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *RconOpenResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RconOpenResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RconOpenResponse) GetAuthFailed() bool {
	if x != nil {
		return x.AuthFailed
	}
	return false
}

func (x *RconOpenResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// RconExecuteRequest carries one fully rendered console command.
type RconExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// protocol_id is the RconProtocol.id this call belongs to.
	ProtocolId string `protobuf:"bytes,1,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	// conn_handle is the handle from the preceding RconOpen, still owned by this
	// plugin and still within its deadline.
	ConnHandle uint64 `protobuf:"varint,2,opt,name=conn_handle,json=connHandle,proto3" json:"conn_handle,omitempty"`
	// command is a single console command, already rendered from the kick/ban
	// template or typed by the panel user. Send it as-is: the host has validated
	// it and does not expect the plugin to split, rewrite or chain commands.
	Command string `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *RconExecuteRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RconExecuteRequest) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

func (x *RconExecuteRequest) GetConnHandle() uint64 {
	if x != nil {
		return x.ConnHandle
	}
	return 0
}

func (x *RconExecuteRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type RconExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// output is the server's raw answer, returned to the panel user verbatim and
	// fed to the players parser for a players_command. An empty output on a
	// silent command is normal.
	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	// error marks the command as failed and replaces the output. Presence alone
	// signals failure, so leave the field unset on success rather than setting
	// it to an empty string.
	Error *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *RconExecuteResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RconExecuteResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RconExecuteResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// RconCloseRequest asks the plugin to end the session politely before the host
// drops the connection.
type RconCloseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// protocol_id is the RconProtocol.id this call belongs to.
	ProtocolId string `protobuf:"bytes,1,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	// conn_handle is the handle being torn down. It is released right after this
	// call returns, whatever the outcome.
	ConnHandle uint64 `protobuf:"varint,2,opt,name=conn_handle,json=connHandle,proto3" json:"conn_handle,omitempty"`
}

func (x *RconCloseRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RconCloseRequest) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

func (x *RconCloseRequest) GetConnHandle() uint64 {
	if x != nil {
		return x.ConnHandle
	}
	return 0
}

type RconCloseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// error is accepted for symmetry but ignored: the host closes and releases
	// the connection regardless, and a failing close is not reported to the
	// panel user.
	Error *string `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *RconCloseResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RconCloseResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// QueryServerRequest asks the plugin to probe a game server for its status.
type QueryServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// protocol_id is the QueryProtocol.id this call belongs to.
	ProtocolId string `protobuf:"bytes,1,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	// conn_handle is an opaque, non-zero handle to a UDP connection the host
	// opened to the game server. Unlike the RCON handles it lives only for this
	// call — the host releases it as soon as QueryServer returns, so nothing may
	// be cached across calls.
	ConnHandle uint64 `protobuf:"varint,2,opt,name=conn_handle,json=connHandle,proto3" json:"conn_handle,omitempty"`
	// address is the "host:port" the host dialled, for logging and for protocols
	// that echo it in the payload.
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *QueryServerRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *QueryServerRequest) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

func (x *QueryServerRequest) GetConnHandle() uint64 {
	if x != nil {
		return x.ConnHandle
	}
	return 0
}

func (x *QueryServerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// QueryResultPlayer is one player from a query response. Query protocols expose
// far less than RCON, so this is deliberately narrower than RconPlayer.
type QueryResultPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the player nickname.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// score as reported by the server; 0 when the protocol carries no score.
	Score int64 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *QueryResultPlayer) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *QueryResultPlayer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryResultPlayer) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// QueryResult is the status of a game server.
type QueryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// online reports that the server answered the probe. Everything else is
	// meaningful only when it is true.
	Online bool `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	// name is the server hostname as advertised.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// map is the current map name.
	Map string `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	// players_num is the current player count.
	PlayersNum int64 `protobuf:"varint,4,opt,name=players_num,json=playersNum,proto3" json:"players_num,omitempty"`
	// max_players_num is the slot limit.
	MaxPlayersNum int64 `protobuf:"varint,5,opt,name=max_players_num,json=maxPlayersNum,proto3" json:"max_players_num,omitempty"`
	// players is the player list, when the protocol carries one. It may be empty
	// (or shorter than players_num) even on a healthy server — many protocols
	// report only counts, and some cap the list.
	Players []*QueryResultPlayer `protobuf:"bytes,6,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *QueryResult) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *QueryResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryResult) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *QueryResult) GetPlayersNum() int64 {
	if x != nil {
		return x.PlayersNum
	}
	return 0
}

func (x *QueryResult) GetMaxPlayersNum() int64 {
	if x != nil {
		return x.MaxPlayersNum
	}
	return 0
}

func (x *QueryResult) GetPlayers() []*QueryResultPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

type QueryServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// result is the server status. A missing result is treated as an empty,
	// offline one, so report a genuine probe failure through error instead.
	Result *QueryResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// error marks the query as failed. As with RconExecuteResponse, presence
	// alone signals failure — leave it unset on success. The query timestamp is
	// stamped by the host, not the plugin.
	Error *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *QueryServerResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *QueryServerResponse) GetResult() *QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *QueryServerResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// ParsePlayersRequest carries a players list for structuring. It is sent only
// for protocols whose PlayerCapability.parse_via_plugin is set, and involves no
// connection: the host has already run players_command over RCON.
type ParsePlayersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// protocol_id is the RconProtocol.id this call belongs to.
	ProtocolId string `protobuf:"bytes,1,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	// raw is the verbatim RCON output of players_command, including any header
	// and trailer lines the server printed.
	Raw string `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *ParsePlayersRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ParsePlayersRequest) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

func (x *ParsePlayersRequest) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

type ParsePlayersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// players is the parsed list. Return an empty list for an empty server;
	// skipping unparsable lines is preferred over failing the whole call, since
	// one malformed entry then does not hide every other player.
	Players []*RconPlayer `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	// error marks parsing as failed. Presence alone signals failure — leave it
	// unset on success.
	Error *string `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *ParsePlayersResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ParsePlayersResponse) GetPlayers() []*RconPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *ParsePlayersResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// ProtocolService is an optional plugin service for extending RCON and Query
// protocols. Plugins implement it in addition to the core PluginService when
// they add games, override built-in protocols, or implement new wire protocols.
//
// The registration RPCs are polled by the host at load time. The execution RPCs
// are called on demand: the host opens and guards the connection to the game
// server and hands the plugin a conn_handle; the plugin performs the wire I/O
// over that handle with the gameap-net host library (it never dials).
//
// Lifecycle
//
//  1. The host loads the plugin and calls GetRconProtocols / GetQueryProtocols
//     exactly once. A plugin that does not export them registers nothing —
//     the failure is logged at debug level and is not fatal.
//  2. Registrations from a disabled plugin are ignored; re-enabling or
//     reloading the plugin re-polls them.
//  3. On every RCON/Query operation the host resolves the game against the
//     plugin registrations first, then against its built-in tables.
//
// # Resolution
//
// The host scans every registration from every enabled plugin for a game_codes
// match, and only if none matched it scans for an engines match. Both are
// compared case-insensitively. Within a pass the first match wins, and
// registrations are pre-sorted by plugin ID, so the alphabetically-first plugin
// deterministically wins a conflict. When nothing matches, the panel falls back
// to its built-in tables.
//
// A registration therefore overrides the built-in mapping for the games it
// claims — including for a broken or unrunnable registration, so declare only
// what the plugin can actually serve.
//
// go:plugin type=plugin version=1
type ProtocolService interface {
	// GetRconProtocols is polled once when the plugin loads. Returning an empty
	// list (or not exporting this RPC) means the plugin adds no RCON protocols.
	GetRconProtocols(context.Context, *GetRconProtocolsRequest) (*GetRconProtocolsResponse, error)
	// GetQueryProtocols is polled once when the plugin loads, like
	// GetRconProtocols.
	GetQueryProtocols(context.Context, *GetQueryProtocolsRequest) (*GetQueryProtocolsResponse, error)
	// RconOpen authenticates a freshly dialled RCON connection. Called only for
	// RCON_TRANSPORT_PLUGIN registrations, once per client, before RconExecute.
	// The host closes and releases the connection if this fails.
	RconOpen(context.Context, *RconOpenRequest) (*RconOpenResponse, error)
	// RconExecute runs one console command on an opened connection and returns
	// its raw output. Called any number of times between RconOpen and RconClose.
	RconExecute(context.Context, *RconExecuteRequest) (*RconExecuteResponse, error)
	// RconClose lets the plugin send a protocol-level goodbye before the host
	// tears the connection down. Best-effort: the host ignores the outcome and
	// releases the connection either way, so implementing it is optional.
	RconClose(context.Context, *RconCloseRequest) (*RconCloseResponse, error)
	// QueryServer probes a game server over a host-opened UDP connection and
	// returns its status. Called for QUERY_TRANSPORT_PLUGIN registrations. The
	// handle is released as soon as this call returns.
	QueryServer(context.Context, *QueryServerRequest) (*QueryServerResponse, error)
	// ParsePlayers turns the raw output of PlayerCapability.players_command into
	// structured players. Called only when parse_via_plugin is set, and unlike
	// the other execution RPCs it involves no connection at all.
	ParsePlayers(context.Context, *ParsePlayersRequest) (*ParsePlayersResponse, error)
}
