GET {{host}}/api/servers/1/abilities
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

GET {{host}}/api/servers/2/abilities
Content-Type: application/json
Authorization: Bearer {{authToken}}