// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: pkg/plugin/sdk/host/host.proto

package host

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGrantsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGrantsRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

type GetGrantsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Permissions []string `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
}

func (x *GetGrantsResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetGrantsResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetHostInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHostInfoRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

type GetHostInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PanelVersion     string `protobuf:"bytes,1,opt,name=panel_version,json=panelVersion,proto3" json:"panel_version,omitempty"`
	PluginApiVersion uint32 `protobuf:"varint,2,opt,name=plugin_api_version,json=pluginApiVersion,proto3" json:"plugin_api_version,omitempty"`
	// Host modules instantiated for this plugin ("gameap-nodefs", ...), sorted.
	Modules []string `protobuf:"bytes,3,rep,name=modules,proto3" json:"modules,omitempty"`
	// Identifier of the panel instance answering the call.
	InstanceId string `protobuf:"bytes,4,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
}

func (x *GetHostInfoResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GetHostInfoResponse) GetPanelVersion() string {
	if x != nil {
		return x.PanelVersion
	}
	return ""
}

func (x *GetHostInfoResponse) GetPluginApiVersion() uint32 {
	if x != nil {
		return x.PluginApiVersion
	}
	return 0
}

func (x *GetHostInfoResponse) GetModules() []string {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *GetHostInfoResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// HostService lets a plugin introspect itself and the panel it runs on: the
// grants it holds and what the host provides. Open to every plugin (no grant,
// no rate limit). Transient loads (dry-run) answer empty grants.
// go:plugin type=host module=gameap-host
type HostService interface {
	// GetGrants answers the permissions the operator granted this plugin,
	// read live from the panel database.
	GetGrants(context.Context, *GetGrantsRequest) (*GetGrantsResponse, error)
	// GetHostInfo describes the panel and the host modules instantiated for
	// this plugin, so a plugin can degrade gracefully instead of failing calls.
	GetHostInfo(context.Context, *GetHostInfoRequest) (*GetHostInfoResponse, error)
}
