//go:build wasip1

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// Patched: response buffers allocated by the host are freed after unmarshal.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: pkg/plugin/sdk/scheduler/scheduler.proto

package scheduler

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
	_ "unsafe"
)

const ScheduledTaskHandlerPluginAPIVersion = 1

//go:wasmexport scheduled_task_handler_api_version
func _scheduled_task_handler_api_version() uint64 {
	return ScheduledTaskHandlerPluginAPIVersion
}

var scheduledTaskHandler ScheduledTaskHandler

func RegisterScheduledTaskHandler(p ScheduledTaskHandler) {
	scheduledTaskHandler = p
}

//go:wasmexport scheduled_task_handler_handle_scheduled_task
func _scheduled_task_handler_handle_scheduled_task(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(HandleScheduledTaskRequest)
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := scheduledTaskHandler.HandleScheduledTask(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

type schedulerService struct{}

func NewSchedulerService() SchedulerService {
	return schedulerService{}
}

//go:wasmimport gameap-scheduler add_task
func _add_task(ptr uint32, size uint32) uint64

func (h schedulerService) AddTask(ctx context.Context, request *AddTaskRequest) (*AddTaskResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _add_task(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(AddTaskResponse)
	err = response.UnmarshalVT(buf)
	if ptr != 0 {
		wasm.Free(ptr)
	}
	if err != nil {
		return nil, err
	}
	return response, nil
}

//go:wasmimport gameap-scheduler remove_task
func _remove_task(ptr uint32, size uint32) uint64

func (h schedulerService) RemoveTask(ctx context.Context, request *RemoveTaskRequest) (*RemoveTaskResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _remove_task(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(RemoveTaskResponse)
	err = response.UnmarshalVT(buf)
	if ptr != 0 {
		wasm.Free(ptr)
	}
	if err != nil {
		return nil, err
	}
	return response, nil
}

//go:wasmimport gameap-scheduler list_tasks
func _list_tasks(ptr uint32, size uint32) uint64

func (h schedulerService) ListTasks(ctx context.Context, request *ListTasksRequest) (*ListTasksResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _list_tasks(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(ListTasksResponse)
	err = response.UnmarshalVT(buf)
	if ptr != 0 {
		wasm.Free(ptr)
	}
	if err != nil {
		return nil, err
	}
	return response, nil
}
