import FileNetworkIcon from './svg/FileNetworkIcon.vue'
import FolderDownloadIcon from './svg/FolderDownloadIcon.vue'
import MaximizeIcon from './svg/MaximizeIcon.vue'
import { svgAsset } from './svgAssets.js'

export const defaultIconMap = {
  // ===== Action Icons =====
  "delete": "fa-solid fa-trash-can",
  "trash": "fa-solid fa-trash",
  "trash-can": "fa-solid fa-trash-can",
  "edit": "fa-solid fa-pen-to-square",
  "pen": "fa-solid fa-pen",
  "pen-ruler": "fa-solid fa-pen-ruler",
  "save": "fa-solid fa-floppy-disk",
  "add": "fa-solid fa-plus",
  "plus": "fa-solid fa-plus",
  "add-square": "fa-solid fa-square-plus",
  "add-folder": "fa-solid fa-folder-plus",
  "close": "fa-solid fa-xmark",
  "xmark": "fa-solid fa-xmark",
  "times": "fa-solid fa-times",
  "copy": "fa-regular fa-copy",
  "paste": "fa-regular fa-paste",
  "cut": "fa-solid fa-scissors",
  "scissors": "fa-solid fa-scissors",
  "refresh": "fa-solid fa-rotate",
  "rotate": "fa-solid fa-rotate",
  "sync": "fa-solid fa-sync",
  "redo": "fa-solid fa-redo",
  "download": "fa-solid fa-download",
  "upload": "fa-solid fa-upload",
  "export": "fa-solid fa-arrow-up-right-from-square",
  "languages": "fa-solid fa-language",
  "search": "fa-solid fa-magnifying-glass",
  "magnifying-glass": "fa-solid fa-magnifying-glass",
  "view": "fa-solid fa-eye",
  "eye": "fa-solid fa-eye",
  "clear": "fa-solid fa-broom",
  "broom": "fa-solid fa-broom",
  "eraser": "fa-solid fa-eraser",
  "ban": "fa-solid fa-ban",
  "move": "fa-solid fa-dolly",
  "maximize": MaximizeIcon,

  // ===== Navigation Icons =====
  "chevron-left": "fa-solid fa-chevron-left",
  "chevron-right": "fa-solid fa-chevron-right",
  "chevron-up": "fa-solid fa-chevron-up",
  "chevron-down": "fa-solid fa-chevron-down",
  "arrow-up": "fa-solid fa-arrow-up",
  "arrow-down": "fa-solid fa-arrow-down",
  "arrow-turn-up": "fa-solid fa-arrow-turn-up",
  "sort-asc": "fa-solid fa-arrow-up-wide-short",
  "sort-desc": "fa-solid fa-arrow-down-wide-short",
  "external-link": "fa-solid fa-external-link",
  "angle-double-right": "fa-solid fa-angle-double-right",
  "chevron-double-right": "fa-solid fa-angle-double-right",

  // ===== Status Icons =====
  "check": "fa-solid fa-check",
  "warning": "fa-solid fa-triangle-exclamation",
  "error": "fa-solid fa-skull",
  "skull": "fa-solid fa-skull",
  "info": "fa-solid fa-circle-info",
  "question": "fa-regular fa-circle-question",
  "help": "fa-regular fa-circle-question",
  "online": "fa-solid fa-heart-pulse",
  "health": "fa-solid fa-heart-pulse",
  "heart-pulse": "fa-solid fa-heart-pulse",
  "offline": "fa-solid fa-power-off",
  "power-off": "fa-solid fa-power-off",
  "certificate": "fa-solid fa-certificate",

  // ===== UI/State Icons =====
  "loading": "fa-solid fa-gear fa-spin",
  "spinner": "fa-solid fa-spinner fa-spin",
  "play": "fa-solid fa-play",
  "pause": "fa-solid fa-pause",
  "stop": "fa-solid fa-stop",
  "restart": "fa-solid fa-redo",

  // ===== Server/Infrastructure Icons =====
  "server": "fa-solid fa-server",
  "node": "fa-solid fa-hard-drive",
  "hard-drive": "fa-solid fa-hard-drive",
  "hdd": "fa-solid fa-hard-drive",
  "terminal": "fa-solid fa-terminal",
  "console": "fa-solid fa-terminal",
  "gamepad": "fa-solid fa-gamepad",
  "tasks": "fa-solid fa-tasks",
  "plug": "fa-solid fa-plug",
  "memory": "fa-solid fa-memory",
  "cpu": "fa-solid fa-microchip",
  "microchip": "fa-solid fa-microchip",
  "metrics": "fa-solid fa-chart-area",

  // ===== User/Auth Icons =====
  "user": "fa-solid fa-user",
  "user-edit": "fa-solid fa-user-pen",
  "user-pen": "fa-solid fa-user-pen",
  "users": "fa-solid fa-users",
  "user-astronaut": "fa-solid fa-user-astronaut",
  "login": "fa-solid fa-right-to-bracket",
  "sign-in": "fa-solid fa-right-to-bracket",
  "logout": "fa-solid fa-sign-out-alt",
  "key": "fa-solid fa-key",
  "lock": "fa-solid fa-lock",
  "address-card": "fa-regular fa-address-card",
  "profile": "fa-regular fa-address-card",

  // ===== File Icons =====
  "file": "fa-regular fa-file",
  "file-code": "fa-regular fa-file-code",
  "file-lines": "fa-regular fa-file-lines",
  "file-text": "fa-regular fa-file-lines",
  "file-pdf": "fa-regular fa-file-pdf",
  "file-word": "fa-regular fa-file-word",
  "file-excel": "fa-regular fa-file-excel",
  "file-powerpoint": "fa-solid fa-file-powerpoint",
  "file-image": "fa-regular fa-file-image",
  "file-video": "fa-regular fa-file-video",
  "file-audio": "fa-regular fa-file-audio",
  "file-archive": "fa-solid fa-file-zipper",
  "file-zipper": "fa-solid fa-file-zipper",
  "box-open": "fa-solid fa-box-open",
  "fingerprint": "fa-solid fa-fingerprint",
  "folder": "fa-regular fa-folder",
  "folder-solid": "fa-solid fa-folder",
  "folder-open": "fa-regular fa-folder-open",
  "folder-plus": "fa-solid fa-folder-plus",
  "folder-download": FolderDownloadIcon,
  "clipboard": "fa-regular fa-clipboard",
  "ftp": FileNetworkIcon,

  // ===== Content/UI Icons =====
  "book": "fa-solid fa-book",
  "comments": "fa-regular fa-comments",
  "heart": "fa-regular fa-heart",
  "favorite": "fa-regular fa-heart",
  "star": "fa-solid fa-star",
  "star-outline": "fa-regular fa-star",
  "crown": "fa-solid fa-crown",
  "puzzle-piece": "fa-solid fa-puzzle-piece",
  "plugin": "fa-solid fa-puzzle-piece",
  "box": "fa-solid fa-box",
  "package": "fa-solid fa-box",
  "cogs": "fa-solid fa-cogs",
  "settings": "fa-solid fa-gear",
  "gear": "fa-solid fa-gear",
  "hammer": "fa-solid fa-hammer",
  "laptop-code": "fa-solid fa-laptop-code",
  "admin-panel": "fa-solid fa-laptop-code",
  "calendar": "fa-solid fa-calendar",
  "scale-balanced": "fa-solid fa-scale-balanced",
  "license": "fa-solid fa-scale-balanced",
  "list": "fa-regular fa-rectangle-list",
  "rcon": "fa-solid fa-reply-all",
  "reply-all": "fa-solid fa-reply-all",

  // ===== Theme Icons =====
  "sun": "fa-solid fa-sun",
  "moon": "fa-solid fa-moon",

  // ===== Game Icons =====
  "dice": "fa-solid fa-dice",
  "dice-one": "fa-solid fa-dice-one",
  "dice-two": "fa-solid fa-dice-two",
  "dice-three": "fa-solid fa-dice-three",
  "dice-four": "fa-solid fa-dice-four",
  "dice-five": "fa-solid fa-dice-five",
  "dice-six": "fa-solid fa-dice-six",
  "7": "fa-solid fa-7",
  "cat": "fa-solid fa-cat",
  "mods": "fa-solid fa-cat",
  "kick": svgAsset('kick'),

  // ===== Game Logos =====
  "game-ark-survival-evolved": svgAsset('ark-survival-evolved'),
  "game-arma-2": svgAsset('arma-2'),
  "game-arma-3": svgAsset('arma-3'),
  "game-black-mesa": svgAsset('black-mesa'),
  "game-counter-strike": svgAsset('counter-strike'),
  "game-counter-strike-1": svgAsset('counter-strike-1'),
  "game-counter-strike-source": svgAsset('counter-strike-source'),
  "game-day-of-defeat": svgAsset('day-of-defeat'),
  "game-dont-starve": svgAsset('dont-starve'),
  "game-enshrouded": svgAsset('enshrouded'),
  "game-etlegacy": svgAsset('etlegacy'),
  "game-factorio": svgAsset('factorio'),
  "game-fivem": svgAsset('fivem'),
  "game-garrys-mod": svgAsset('garrys-mod'),
  "game-grand-theft-auto": svgAsset('grand-theft-auto'),
  "game-half-life": svgAsset('half-life'),
  "game-hurtworld": svgAsset('hurtworld'),
  "game-left-4-dead": svgAsset('left-4-dead'),
  "game-minecraft": svgAsset('minecraft'),
  "game-minecraft-creeper": svgAsset('minecraft-creeper'),
  "game-palworld": svgAsset('palworld'),
  "game-quake": svgAsset('quake'),
  "game-quake-2": svgAsset('quake-2'),
  "game-quake-3": svgAsset('quake-3'),
  "game-rockstar": svgAsset('rockstar'),
  "game-rust": svgAsset('rust'),
  "game-team-fortress-2": svgAsset('team-fortress-2'),
  "game-zomboid": svgAsset('zomboid'),

  // ===== Brand Icons =====
  "gameap": svgAsset('gameap'),
  "linux": "fa-brands fa-linux",
  "windows": "fa-brands fa-windows",
  "apple": "fa-brands fa-apple",
  "telegram": "fa-brands fa-telegram",
  "discord": "fa-brands fa-discord",
  "vk": "fa-brands fa-vk",
  "reddit": "fa-brands fa-reddit",
  "patreon": "fa-brands fa-patreon",
  "teamspeak": "fa-brands fa-teamspeak",
}
