//go:build wasip1

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// Patched: response buffers allocated by the host are freed after unmarshal.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: pkg/plugin/sdk/storage/storage.proto

package storage

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
	_ "unsafe"
)

type storageService struct{}

func NewStorageService() StorageService {
	return storageService{}
}

//go:wasmimport gameap-storage get
func _get(ptr uint32, size uint32) uint64

func (h storageService) Get(ctx context.Context, request *StorageGetRequest) (*StorageGetResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _get(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(StorageGetResponse)
	err = response.UnmarshalVT(buf)
	if ptr != 0 {
		wasm.Free(ptr)
	}
	if err != nil {
		return nil, err
	}
	return response, nil
}

//go:wasmimport gameap-storage set
func _set(ptr uint32, size uint32) uint64

func (h storageService) Set(ctx context.Context, request *StorageSetRequest) (*StorageSetResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _set(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(StorageSetResponse)
	err = response.UnmarshalVT(buf)
	if ptr != 0 {
		wasm.Free(ptr)
	}
	if err != nil {
		return nil, err
	}
	return response, nil
}

//go:wasmimport gameap-storage delete
func _delete(ptr uint32, size uint32) uint64

func (h storageService) Delete(ctx context.Context, request *StorageDeleteRequest) (*StorageDeleteResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _delete(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(StorageDeleteResponse)
	err = response.UnmarshalVT(buf)
	if ptr != 0 {
		wasm.Free(ptr)
	}
	if err != nil {
		return nil, err
	}
	return response, nil
}

//go:wasmimport gameap-storage list
func _list(ptr uint32, size uint32) uint64

func (h storageService) List(ctx context.Context, request *StorageListRequest) (*StorageListResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _list(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(StorageListResponse)
	err = response.UnmarshalVT(buf)
	if ptr != 0 {
		wasm.Free(ptr)
	}
	if err != nil {
		return nil, err
	}
	return response, nil
}
