// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: pkg/proto/node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled     bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name        string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Os          string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Location    string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Provider    *string                `protobuf:"bytes,6,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	Ips         []string               `protobuf:"bytes,7,rep,name=ips,proto3" json:"ips,omitempty"`
	WorkPath    string                 `protobuf:"bytes,8,opt,name=work_path,json=workPath,proto3" json:"work_path,omitempty"`
	GdaemonHost string                 `protobuf:"bytes,9,opt,name=gdaemon_host,json=gdaemonHost,proto3" json:"gdaemon_host,omitempty"`
	GdaemonPort int32                  `protobuf:"varint,10,opt,name=gdaemon_port,json=gdaemonPort,proto3" json:"gdaemon_port,omitempty"`
	// Unix seconds.
	CreatedAt *int64 `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	UpdatedAt *int64 `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	// Free-form node tags. Values are always strings here: the panel stores the
	// bag as arbitrary JSON, and non-string entries written through the HTTP API
	// are rendered (numbers and booleans via strconv, anything else as JSON).
	Metadata      map[string]string `protobuf:"bytes,13,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_pkg_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_pkg_proto_node_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Node) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Node) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *Node) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *Node) GetWorkPath() string {
	if x != nil {
		return x.WorkPath
	}
	return ""
}

func (x *Node) GetGdaemonHost() string {
	if x != nil {
		return x.GdaemonHost
	}
	return ""
}

func (x *Node) GetGdaemonPort() int32 {
	if x != nil {
		return x.GdaemonPort
	}
	return 0
}

func (x *Node) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *Node) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

func (x *Node) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_pkg_proto_node_proto protoreflect.FileDescriptor

const file_pkg_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/node.proto\x12\x06gameap\"\xee\x03\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x1f\n" +
	"\bprovider\x18\x06 \x01(\tH\x00R\bprovider\x88\x01\x01\x12\x10\n" +
	"\x03ips\x18\a \x03(\tR\x03ips\x12\x1b\n" +
	"\twork_path\x18\b \x01(\tR\bworkPath\x12!\n" +
	"\fgdaemon_host\x18\t \x01(\tR\vgdaemonHost\x12!\n" +
	"\fgdaemon_port\x18\n" +
	" \x01(\x05R\vgdaemonPort\x12\"\n" +
	"\n" +
	"created_at\x18\v \x01(\x03H\x01R\tcreatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"updated_at\x18\f \x01(\x03H\x02R\tupdatedAt\x88\x01\x01\x126\n" +
	"\bmetadata\x18\r \x03(\v2\x1a.gameap.Node.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_providerB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_atB$Z\"github.com/gameap/gameap/pkg/protob\x06proto3"

var (
	file_pkg_proto_node_proto_rawDescOnce sync.Once
	file_pkg_proto_node_proto_rawDescData []byte
)

func file_pkg_proto_node_proto_rawDescGZIP() []byte {
	file_pkg_proto_node_proto_rawDescOnce.Do(func() {
		file_pkg_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_node_proto_rawDesc), len(file_pkg_proto_node_proto_rawDesc)))
	})
	return file_pkg_proto_node_proto_rawDescData
}

var file_pkg_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_node_proto_goTypes = []any{
	(*Node)(nil), // 0: gameap.Node
	nil,          // 1: gameap.Node.MetadataEntry
}
var file_pkg_proto_node_proto_depIdxs = []int32{
	1, // 0: gameap.Node.metadata:type_name -> gameap.Node.MetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_node_proto_init() }
func file_pkg_proto_node_proto_init() {
	if File_pkg_proto_node_proto != nil {
		return
	}
	file_pkg_proto_node_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_node_proto_rawDesc), len(file_pkg_proto_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_node_proto_goTypes,
		DependencyIndexes: file_pkg_proto_node_proto_depIdxs,
		MessageInfos:      file_pkg_proto_node_proto_msgTypes,
	}.Build()
	File_pkg_proto_node_proto = out.File
	file_pkg_proto_node_proto_goTypes = nil
	file_pkg_proto_node_proto_depIdxs = nil
}
