// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: pkg/proto/servertask.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerTaskCommand int32

const (
	ServerTaskCommand_SERVER_TASK_COMMAND_UNSPECIFIED ServerTaskCommand = 0
	ServerTaskCommand_SERVER_TASK_COMMAND_START       ServerTaskCommand = 1
	ServerTaskCommand_SERVER_TASK_COMMAND_STOP        ServerTaskCommand = 2
	ServerTaskCommand_SERVER_TASK_COMMAND_RESTART     ServerTaskCommand = 3
	ServerTaskCommand_SERVER_TASK_COMMAND_UPDATE      ServerTaskCommand = 4
	ServerTaskCommand_SERVER_TASK_COMMAND_REINSTALL   ServerTaskCommand = 5
)

// Enum value maps for ServerTaskCommand.
var (
	ServerTaskCommand_name = map[int32]string{
		0: "SERVER_TASK_COMMAND_UNSPECIFIED",
		1: "SERVER_TASK_COMMAND_START",
		2: "SERVER_TASK_COMMAND_STOP",
		3: "SERVER_TASK_COMMAND_RESTART",
		4: "SERVER_TASK_COMMAND_UPDATE",
		5: "SERVER_TASK_COMMAND_REINSTALL",
	}
	ServerTaskCommand_value = map[string]int32{
		"SERVER_TASK_COMMAND_UNSPECIFIED": 0,
		"SERVER_TASK_COMMAND_START":       1,
		"SERVER_TASK_COMMAND_STOP":        2,
		"SERVER_TASK_COMMAND_RESTART":     3,
		"SERVER_TASK_COMMAND_UPDATE":      4,
		"SERVER_TASK_COMMAND_REINSTALL":   5,
	}
)

func (x ServerTaskCommand) Enum() *ServerTaskCommand {
	p := new(ServerTaskCommand)
	*p = x
	return p
}

func (x ServerTaskCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerTaskCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_servertask_proto_enumTypes[0].Descriptor()
}

func (ServerTaskCommand) Type() protoreflect.EnumType {
	return &file_pkg_proto_servertask_proto_enumTypes[0]
}

func (x ServerTaskCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerTaskCommand.Descriptor instead.
func (ServerTaskCommand) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{0}
}

type ServerTaskOverlapPolicy int32

const (
	ServerTaskOverlapPolicy_SERVER_TASK_OVERLAP_POLICY_UNSPECIFIED ServerTaskOverlapPolicy = 0
	ServerTaskOverlapPolicy_SERVER_TASK_OVERLAP_POLICY_SKIP        ServerTaskOverlapPolicy = 1
	ServerTaskOverlapPolicy_SERVER_TASK_OVERLAP_POLICY_QUEUE       ServerTaskOverlapPolicy = 2
)

// Enum value maps for ServerTaskOverlapPolicy.
var (
	ServerTaskOverlapPolicy_name = map[int32]string{
		0: "SERVER_TASK_OVERLAP_POLICY_UNSPECIFIED",
		1: "SERVER_TASK_OVERLAP_POLICY_SKIP",
		2: "SERVER_TASK_OVERLAP_POLICY_QUEUE",
	}
	ServerTaskOverlapPolicy_value = map[string]int32{
		"SERVER_TASK_OVERLAP_POLICY_UNSPECIFIED": 0,
		"SERVER_TASK_OVERLAP_POLICY_SKIP":        1,
		"SERVER_TASK_OVERLAP_POLICY_QUEUE":       2,
	}
)

func (x ServerTaskOverlapPolicy) Enum() *ServerTaskOverlapPolicy {
	p := new(ServerTaskOverlapPolicy)
	*p = x
	return p
}

func (x ServerTaskOverlapPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerTaskOverlapPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_servertask_proto_enumTypes[1].Descriptor()
}

func (ServerTaskOverlapPolicy) Type() protoreflect.EnumType {
	return &file_pkg_proto_servertask_proto_enumTypes[1]
}

func (x ServerTaskOverlapPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerTaskOverlapPolicy.Descriptor instead.
func (ServerTaskOverlapPolicy) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{1}
}

type ServerTaskCatchupPolicy int32

const (
	ServerTaskCatchupPolicy_SERVER_TASK_CATCHUP_POLICY_UNSPECIFIED ServerTaskCatchupPolicy = 0
	ServerTaskCatchupPolicy_SERVER_TASK_CATCHUP_POLICY_SKIP        ServerTaskCatchupPolicy = 1
	ServerTaskCatchupPolicy_SERVER_TASK_CATCHUP_POLICY_RUN_ONCE    ServerTaskCatchupPolicy = 2
)

// Enum value maps for ServerTaskCatchupPolicy.
var (
	ServerTaskCatchupPolicy_name = map[int32]string{
		0: "SERVER_TASK_CATCHUP_POLICY_UNSPECIFIED",
		1: "SERVER_TASK_CATCHUP_POLICY_SKIP",
		2: "SERVER_TASK_CATCHUP_POLICY_RUN_ONCE",
	}
	ServerTaskCatchupPolicy_value = map[string]int32{
		"SERVER_TASK_CATCHUP_POLICY_UNSPECIFIED": 0,
		"SERVER_TASK_CATCHUP_POLICY_SKIP":        1,
		"SERVER_TASK_CATCHUP_POLICY_RUN_ONCE":    2,
	}
)

func (x ServerTaskCatchupPolicy) Enum() *ServerTaskCatchupPolicy {
	p := new(ServerTaskCatchupPolicy)
	*p = x
	return p
}

func (x ServerTaskCatchupPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerTaskCatchupPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_servertask_proto_enumTypes[2].Descriptor()
}

func (ServerTaskCatchupPolicy) Type() protoreflect.EnumType {
	return &file_pkg_proto_servertask_proto_enumTypes[2]
}

func (x ServerTaskCatchupPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerTaskCatchupPolicy.Descriptor instead.
func (ServerTaskCatchupPolicy) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{2}
}

type ServerTaskExecutionStatus int32

const (
	ServerTaskExecutionStatus_SERVER_TASK_EXECUTION_STATUS_UNSPECIFIED ServerTaskExecutionStatus = 0
	ServerTaskExecutionStatus_SERVER_TASK_EXECUTION_STATUS_RUNNING     ServerTaskExecutionStatus = 1
	ServerTaskExecutionStatus_SERVER_TASK_EXECUTION_STATUS_SUCCESS     ServerTaskExecutionStatus = 2
	ServerTaskExecutionStatus_SERVER_TASK_EXECUTION_STATUS_FAILED      ServerTaskExecutionStatus = 3
	ServerTaskExecutionStatus_SERVER_TASK_EXECUTION_STATUS_CANCELED    ServerTaskExecutionStatus = 4
	ServerTaskExecutionStatus_SERVER_TASK_EXECUTION_STATUS_SKIPPED     ServerTaskExecutionStatus = 5
	ServerTaskExecutionStatus_SERVER_TASK_EXECUTION_STATUS_TIMED_OUT   ServerTaskExecutionStatus = 6
)

// Enum value maps for ServerTaskExecutionStatus.
var (
	ServerTaskExecutionStatus_name = map[int32]string{
		0: "SERVER_TASK_EXECUTION_STATUS_UNSPECIFIED",
		1: "SERVER_TASK_EXECUTION_STATUS_RUNNING",
		2: "SERVER_TASK_EXECUTION_STATUS_SUCCESS",
		3: "SERVER_TASK_EXECUTION_STATUS_FAILED",
		4: "SERVER_TASK_EXECUTION_STATUS_CANCELED",
		5: "SERVER_TASK_EXECUTION_STATUS_SKIPPED",
		6: "SERVER_TASK_EXECUTION_STATUS_TIMED_OUT",
	}
	ServerTaskExecutionStatus_value = map[string]int32{
		"SERVER_TASK_EXECUTION_STATUS_UNSPECIFIED": 0,
		"SERVER_TASK_EXECUTION_STATUS_RUNNING":     1,
		"SERVER_TASK_EXECUTION_STATUS_SUCCESS":     2,
		"SERVER_TASK_EXECUTION_STATUS_FAILED":      3,
		"SERVER_TASK_EXECUTION_STATUS_CANCELED":    4,
		"SERVER_TASK_EXECUTION_STATUS_SKIPPED":     5,
		"SERVER_TASK_EXECUTION_STATUS_TIMED_OUT":   6,
	}
)

func (x ServerTaskExecutionStatus) Enum() *ServerTaskExecutionStatus {
	p := new(ServerTaskExecutionStatus)
	*p = x
	return p
}

func (x ServerTaskExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerTaskExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_servertask_proto_enumTypes[3].Descriptor()
}

func (ServerTaskExecutionStatus) Type() protoreflect.EnumType {
	return &file_pkg_proto_servertask_proto_enumTypes[3]
}

func (x ServerTaskExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerTaskExecutionStatus.Descriptor instead.
func (ServerTaskExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{3}
}

// Schedule definition shipped to the daemon. The daemon owns the cron tick;
// the API only persists/edits the schedule and consumes execution events.
//
// `version` is monotonic per task_id. Daemons MUST drop deltas whose
// version <= cached version (ordering / late-message safety).
//
// `payload` is opaque application-level data. The daemon stores and passes
// it back unmodified in `ServerTaskExecutionStarted` /
// `ServerTaskExecutionFinished`.
type ServerTask struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            uint64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId      uint64                  `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	NodeId        uint64                  `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Command       ServerTaskCommand       `protobuf:"varint,4,opt,name=command,proto3,enum=gameap.ServerTaskCommand" json:"command,omitempty"`
	ExecuteDate   *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=execute_date,json=executeDate,proto3" json:"execute_date,omitempty"`
	RepeatPeriod  *durationpb.Duration    `protobuf:"bytes,6,opt,name=repeat_period,json=repeatPeriod,proto3" json:"repeat_period,omitempty"`
	RepeatCount   uint32                  `protobuf:"varint,7,opt,name=repeat_count,json=repeatCount,proto3" json:"repeat_count,omitempty"`
	Counter       uint32                  `protobuf:"varint,8,opt,name=counter,proto3" json:"counter,omitempty"`
	Payload       string                  `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	Version       uint64                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	OverlapPolicy ServerTaskOverlapPolicy `protobuf:"varint,11,opt,name=overlap_policy,json=overlapPolicy,proto3,enum=gameap.ServerTaskOverlapPolicy" json:"overlap_policy,omitempty"`
	CatchupPolicy ServerTaskCatchupPolicy `protobuf:"varint,12,opt,name=catchup_policy,json=catchupPolicy,proto3,enum=gameap.ServerTaskCatchupPolicy" json:"catchup_policy,omitempty"`
	Enabled       bool                    `protobuf:"varint,13,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Name          string                  `protobuf:"bytes,14,opt,name=name,proto3" json:"name,omitempty"`
	Timezone      string                  `protobuf:"bytes,15,opt,name=timezone,proto3" json:"timezone,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerTask) Reset() {
	*x = ServerTask{}
	mi := &file_pkg_proto_servertask_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTask) ProtoMessage() {}

func (x *ServerTask) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_servertask_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTask.ProtoReflect.Descriptor instead.
func (*ServerTask) Descriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{0}
}

func (x *ServerTask) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServerTask) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServerTask) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ServerTask) GetCommand() ServerTaskCommand {
	if x != nil {
		return x.Command
	}
	return ServerTaskCommand_SERVER_TASK_COMMAND_UNSPECIFIED
}

func (x *ServerTask) GetExecuteDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecuteDate
	}
	return nil
}

func (x *ServerTask) GetRepeatPeriod() *durationpb.Duration {
	if x != nil {
		return x.RepeatPeriod
	}
	return nil
}

func (x *ServerTask) GetRepeatCount() uint32 {
	if x != nil {
		return x.RepeatCount
	}
	return 0
}

func (x *ServerTask) GetCounter() uint32 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *ServerTask) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ServerTask) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ServerTask) GetOverlapPolicy() ServerTaskOverlapPolicy {
	if x != nil {
		return x.OverlapPolicy
	}
	return ServerTaskOverlapPolicy_SERVER_TASK_OVERLAP_POLICY_UNSPECIFIED
}

func (x *ServerTask) GetCatchupPolicy() ServerTaskCatchupPolicy {
	if x != nil {
		return x.CatchupPolicy
	}
	return ServerTaskCatchupPolicy_SERVER_TASK_CATCHUP_POLICY_UNSPECIFIED
}

func (x *ServerTask) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ServerTask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerTask) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *ServerTask) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Full snapshot delivered in `RegisterAck.server_task_snapshot` and on
// explicit `ServerTaskResyncRequest`. Daemon replaces its local cache
// wholesale.
type ServerTaskSnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tasks           []*ServerTask          `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	SnapshotVersion uint64                 `protobuf:"varint,2,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	GeneratedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerTaskSnapshot) Reset() {
	*x = ServerTaskSnapshot{}
	mi := &file_pkg_proto_servertask_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTaskSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTaskSnapshot) ProtoMessage() {}

func (x *ServerTaskSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_servertask_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTaskSnapshot.ProtoReflect.Descriptor instead.
func (*ServerTaskSnapshot) Descriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{1}
}

func (x *ServerTaskSnapshot) GetTasks() []*ServerTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ServerTaskSnapshot) GetSnapshotVersion() uint64 {
	if x != nil {
		return x.SnapshotVersion
	}
	return 0
}

func (x *ServerTaskSnapshot) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type ServerTaskDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerTaskDeleted) Reset() {
	*x = ServerTaskDeleted{}
	mi := &file_pkg_proto_servertask_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTaskDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTaskDeleted) ProtoMessage() {}

func (x *ServerTaskDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_servertask_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTaskDeleted.ProtoReflect.Descriptor instead.
func (*ServerTaskDeleted) Descriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{2}
}

func (x *ServerTaskDeleted) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServerTaskDeleted) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Incremental update: API → daemon on CRUD.
type ServerTaskDelta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ServerTaskDelta_Upserted
	//	*ServerTaskDelta_Deleted
	Kind          isServerTaskDelta_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerTaskDelta) Reset() {
	*x = ServerTaskDelta{}
	mi := &file_pkg_proto_servertask_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTaskDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTaskDelta) ProtoMessage() {}

func (x *ServerTaskDelta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_servertask_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTaskDelta.ProtoReflect.Descriptor instead.
func (*ServerTaskDelta) Descriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{3}
}

func (x *ServerTaskDelta) GetKind() isServerTaskDelta_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ServerTaskDelta) GetUpserted() *ServerTask {
	if x != nil {
		if x, ok := x.Kind.(*ServerTaskDelta_Upserted); ok {
			return x.Upserted
		}
	}
	return nil
}

func (x *ServerTaskDelta) GetDeleted() *ServerTaskDeleted {
	if x != nil {
		if x, ok := x.Kind.(*ServerTaskDelta_Deleted); ok {
			return x.Deleted
		}
	}
	return nil
}

type isServerTaskDelta_Kind interface {
	isServerTaskDelta_Kind()
}

type ServerTaskDelta_Upserted struct {
	Upserted *ServerTask `protobuf:"bytes,1,opt,name=upserted,proto3,oneof"`
}

type ServerTaskDelta_Deleted struct {
	Deleted *ServerTaskDeleted `protobuf:"bytes,2,opt,name=deleted,proto3,oneof"`
}

func (*ServerTaskDelta_Upserted) isServerTaskDelta_Kind() {}

func (*ServerTaskDelta_Deleted) isServerTaskDelta_Kind() {}

// Daemon → API. Triggered when the daemon suspects its local cache is
// stale (e.g. version gap detected). API replies by sending a fresh
// `ServerTaskSnapshot` on the stream.
type ServerTaskResyncRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	LastKnownSnapshotVersion uint64                 `protobuf:"varint,1,opt,name=last_known_snapshot_version,json=lastKnownSnapshotVersion,proto3" json:"last_known_snapshot_version,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ServerTaskResyncRequest) Reset() {
	*x = ServerTaskResyncRequest{}
	mi := &file_pkg_proto_servertask_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTaskResyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTaskResyncRequest) ProtoMessage() {}

func (x *ServerTaskResyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_servertask_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTaskResyncRequest.ProtoReflect.Descriptor instead.
func (*ServerTaskResyncRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{4}
}

func (x *ServerTaskResyncRequest) GetLastKnownSnapshotVersion() uint64 {
	if x != nil {
		return x.LastKnownSnapshotVersion
	}
	return 0
}

// Daemon → API. Emitted when the daemon's scheduler fires a task. The
// daemon generates `execution_id` (UUIDv4) as the idempotency key — the
// API uses ON CONFLICT (execution_id) DO NOTHING.
//
// `task_version` is the version on which this run is based. If the user
// edits the task mid-run, the recorded execution still reflects the
// version actually executed.
type ServerTaskExecutionStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TaskId        uint64                 `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskVersion   uint64                 `protobuf:"varint,3,opt,name=task_version,json=taskVersion,proto3" json:"task_version,omitempty"`
	ServerId      uint64                 `protobuf:"varint,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	NodeId        uint64                 `protobuf:"varint,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Command       ServerTaskCommand      `protobuf:"varint,6,opt,name=command,proto3,enum=gameap.ServerTaskCommand" json:"command,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerTaskExecutionStarted) Reset() {
	*x = ServerTaskExecutionStarted{}
	mi := &file_pkg_proto_servertask_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTaskExecutionStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTaskExecutionStarted) ProtoMessage() {}

func (x *ServerTaskExecutionStarted) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_servertask_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTaskExecutionStarted.ProtoReflect.Descriptor instead.
func (*ServerTaskExecutionStarted) Descriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{5}
}

func (x *ServerTaskExecutionStarted) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ServerTaskExecutionStarted) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ServerTaskExecutionStarted) GetTaskVersion() uint64 {
	if x != nil {
		return x.TaskVersion
	}
	return 0
}

func (x *ServerTaskExecutionStarted) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ServerTaskExecutionStarted) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ServerTaskExecutionStarted) GetCommand() ServerTaskCommand {
	if x != nil {
		return x.Command
	}
	return ServerTaskCommand_SERVER_TASK_COMMAND_UNSPECIFIED
}

func (x *ServerTaskExecutionStarted) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

// Daemon → API. Sent when execution terminates. For small output the
// daemon sets `output_inline` (≤64 KB). For large output it streams
// chunks via `ServerTaskExecutionLog` during the run and sets
// `output_streamed=true` + `output_storage_path` here.
type ServerTaskExecutionFinished struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	ExecutionId       string                    `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TaskId            uint64                    `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status            ServerTaskExecutionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=gameap.ServerTaskExecutionStatus" json:"status,omitempty"`
	ExitCode          int32                     `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMessage      string                    `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FinishedAt        *timestamppb.Timestamp    `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Duration          *durationpb.Duration      `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	OutputInline      []byte                    `protobuf:"bytes,8,opt,name=output_inline,json=outputInline,proto3" json:"output_inline,omitempty"`
	OutputStreamed    bool                      `protobuf:"varint,9,opt,name=output_streamed,json=outputStreamed,proto3" json:"output_streamed,omitempty"`
	OutputStoragePath string                    `protobuf:"bytes,10,opt,name=output_storage_path,json=outputStoragePath,proto3" json:"output_storage_path,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServerTaskExecutionFinished) Reset() {
	*x = ServerTaskExecutionFinished{}
	mi := &file_pkg_proto_servertask_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTaskExecutionFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTaskExecutionFinished) ProtoMessage() {}

func (x *ServerTaskExecutionFinished) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_servertask_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTaskExecutionFinished.ProtoReflect.Descriptor instead.
func (*ServerTaskExecutionFinished) Descriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{6}
}

func (x *ServerTaskExecutionFinished) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ServerTaskExecutionFinished) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ServerTaskExecutionFinished) GetStatus() ServerTaskExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ServerTaskExecutionStatus_SERVER_TASK_EXECUTION_STATUS_UNSPECIFIED
}

func (x *ServerTaskExecutionFinished) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ServerTaskExecutionFinished) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ServerTaskExecutionFinished) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *ServerTaskExecutionFinished) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *ServerTaskExecutionFinished) GetOutputInline() []byte {
	if x != nil {
		return x.OutputInline
	}
	return nil
}

func (x *ServerTaskExecutionFinished) GetOutputStreamed() bool {
	if x != nil {
		return x.OutputStreamed
	}
	return false
}

func (x *ServerTaskExecutionFinished) GetOutputStoragePath() string {
	if x != nil {
		return x.OutputStoragePath
	}
	return ""
}

// Daemon → API. Optional log chunks for large output, ordered by
// `sequence`. The API streams them to file-transfer storage keyed by
// `execution_id`.
type ServerTaskExecutionLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`
	IsFinal       bool                   `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerTaskExecutionLog) Reset() {
	*x = ServerTaskExecutionLog{}
	mi := &file_pkg_proto_servertask_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTaskExecutionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTaskExecutionLog) ProtoMessage() {}

func (x *ServerTaskExecutionLog) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_servertask_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTaskExecutionLog.ProtoReflect.Descriptor instead.
func (*ServerTaskExecutionLog) Descriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{7}
}

func (x *ServerTaskExecutionLog) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ServerTaskExecutionLog) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ServerTaskExecutionLog) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ServerTaskExecutionLog) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

// API → daemon. Request cancellation of an in-flight execution.
type ServerTaskExecutionCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TaskId        uint64                 `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerTaskExecutionCancel) Reset() {
	*x = ServerTaskExecutionCancel{}
	mi := &file_pkg_proto_servertask_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTaskExecutionCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTaskExecutionCancel) ProtoMessage() {}

func (x *ServerTaskExecutionCancel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_servertask_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTaskExecutionCancel.ProtoReflect.Descriptor instead.
func (*ServerTaskExecutionCancel) Descriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{8}
}

func (x *ServerTaskExecutionCancel) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ServerTaskExecutionCancel) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ServerTaskExecutionCancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// API → daemon. Acknowledge receipt of a finished execution. Daemon
// drops the local "pending ack" buffer entry on receipt.
type ServerTaskExecutionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerTaskExecutionAck) Reset() {
	*x = ServerTaskExecutionAck{}
	mi := &file_pkg_proto_servertask_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerTaskExecutionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerTaskExecutionAck) ProtoMessage() {}

func (x *ServerTaskExecutionAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_servertask_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerTaskExecutionAck.ProtoReflect.Descriptor instead.
func (*ServerTaskExecutionAck) Descriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{9}
}

func (x *ServerTaskExecutionAck) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

// Reported by daemon on register so the API can reconcile rows left in
// `running` state by the previous session.
type InFlightServerTaskExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TaskId        uint64                 `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InFlightServerTaskExecution) Reset() {
	*x = InFlightServerTaskExecution{}
	mi := &file_pkg_proto_servertask_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InFlightServerTaskExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InFlightServerTaskExecution) ProtoMessage() {}

func (x *InFlightServerTaskExecution) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_servertask_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InFlightServerTaskExecution.ProtoReflect.Descriptor instead.
func (*InFlightServerTaskExecution) Descriptor() ([]byte, []int) {
	return file_pkg_proto_servertask_proto_rawDescGZIP(), []int{10}
}

func (x *InFlightServerTaskExecution) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *InFlightServerTaskExecution) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *InFlightServerTaskExecution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

var File_pkg_proto_servertask_proto protoreflect.FileDescriptor

const file_pkg_proto_servertask_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/proto/servertask.proto\x12\x06gameap\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x8c\x05\n" +
	"\n" +
	"ServerTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\x04R\bserverId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x04R\x06nodeId\x123\n" +
	"\acommand\x18\x04 \x01(\x0e2\x19.gameap.ServerTaskCommandR\acommand\x12=\n" +
	"\fexecute_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vexecuteDate\x12>\n" +
	"\rrepeat_period\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\frepeatPeriod\x12!\n" +
	"\frepeat_count\x18\a \x01(\rR\vrepeatCount\x12\x18\n" +
	"\acounter\x18\b \x01(\rR\acounter\x12\x18\n" +
	"\apayload\x18\t \x01(\tR\apayload\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x04R\aversion\x12F\n" +
	"\x0eoverlap_policy\x18\v \x01(\x0e2\x1f.gameap.ServerTaskOverlapPolicyR\roverlapPolicy\x12F\n" +
	"\x0ecatchup_policy\x18\f \x01(\x0e2\x1f.gameap.ServerTaskCatchupPolicyR\rcatchupPolicy\x12\x18\n" +
	"\aenabled\x18\r \x01(\bR\aenabled\x12\x12\n" +
	"\x04name\x18\x0e \x01(\tR\x04name\x12\x1a\n" +
	"\btimezone\x18\x0f \x01(\tR\btimezone\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa8\x01\n" +
	"\x12ServerTaskSnapshot\x12(\n" +
	"\x05tasks\x18\x01 \x03(\v2\x12.gameap.ServerTaskR\x05tasks\x12)\n" +
	"\x10snapshot_version\x18\x02 \x01(\x04R\x0fsnapshotVersion\x12=\n" +
	"\fgenerated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"=\n" +
	"\x11ServerTaskDeleted\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"\x82\x01\n" +
	"\x0fServerTaskDelta\x120\n" +
	"\bupserted\x18\x01 \x01(\v2\x12.gameap.ServerTaskH\x00R\bupserted\x125\n" +
	"\adeleted\x18\x02 \x01(\v2\x19.gameap.ServerTaskDeletedH\x00R\adeletedB\x06\n" +
	"\x04kind\"X\n" +
	"\x17ServerTaskResyncRequest\x12=\n" +
	"\x1blast_known_snapshot_version\x18\x01 \x01(\x04R\x18lastKnownSnapshotVersion\"\xa1\x02\n" +
	"\x1aServerTaskExecutionStarted\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x04R\x06taskId\x12!\n" +
	"\ftask_version\x18\x03 \x01(\x04R\vtaskVersion\x12\x1b\n" +
	"\tserver_id\x18\x04 \x01(\x04R\bserverId\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\x04R\x06nodeId\x123\n" +
	"\acommand\x18\x06 \x01(\x0e2\x19.gameap.ServerTaskCommandR\acommand\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\xc8\x03\n" +
	"\x1bServerTaskExecutionFinished\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x04R\x06taskId\x129\n" +
	"\x06status\x18\x03 \x01(\x0e2!.gameap.ServerTaskExecutionStatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12;\n" +
	"\vfinished_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x125\n" +
	"\bduration\x18\a \x01(\v2\x19.google.protobuf.DurationR\bduration\x12#\n" +
	"\routput_inline\x18\b \x01(\fR\foutputInline\x12'\n" +
	"\x0foutput_streamed\x18\t \x01(\bR\x0eoutputStreamed\x12.\n" +
	"\x13output_storage_path\x18\n" +
	" \x01(\tR\x11outputStoragePath\"\x88\x01\n" +
	"\x16ServerTaskExecutionLog\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\fR\x05chunk\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinal\"o\n" +
	"\x19ServerTaskExecutionCancel\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x04R\x06taskId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\";\n" +
	"\x16ServerTaskExecutionAck\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\x94\x01\n" +
	"\x1bInFlightServerTaskExecution\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x04R\x06taskId\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt*\xd9\x01\n" +
	"\x11ServerTaskCommand\x12#\n" +
	"\x1fSERVER_TASK_COMMAND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SERVER_TASK_COMMAND_START\x10\x01\x12\x1c\n" +
	"\x18SERVER_TASK_COMMAND_STOP\x10\x02\x12\x1f\n" +
	"\x1bSERVER_TASK_COMMAND_RESTART\x10\x03\x12\x1e\n" +
	"\x1aSERVER_TASK_COMMAND_UPDATE\x10\x04\x12!\n" +
	"\x1dSERVER_TASK_COMMAND_REINSTALL\x10\x05*\x90\x01\n" +
	"\x17ServerTaskOverlapPolicy\x12*\n" +
	"&SERVER_TASK_OVERLAP_POLICY_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSERVER_TASK_OVERLAP_POLICY_SKIP\x10\x01\x12$\n" +
	" SERVER_TASK_OVERLAP_POLICY_QUEUE\x10\x02*\x93\x01\n" +
	"\x17ServerTaskCatchupPolicy\x12*\n" +
	"&SERVER_TASK_CATCHUP_POLICY_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSERVER_TASK_CATCHUP_POLICY_SKIP\x10\x01\x12'\n" +
	"#SERVER_TASK_CATCHUP_POLICY_RUN_ONCE\x10\x02*\xc7\x02\n" +
	"\x19ServerTaskExecutionStatus\x12,\n" +
	"(SERVER_TASK_EXECUTION_STATUS_UNSPECIFIED\x10\x00\x12(\n" +
	"$SERVER_TASK_EXECUTION_STATUS_RUNNING\x10\x01\x12(\n" +
	"$SERVER_TASK_EXECUTION_STATUS_SUCCESS\x10\x02\x12'\n" +
	"#SERVER_TASK_EXECUTION_STATUS_FAILED\x10\x03\x12)\n" +
	"%SERVER_TASK_EXECUTION_STATUS_CANCELED\x10\x04\x12(\n" +
	"$SERVER_TASK_EXECUTION_STATUS_SKIPPED\x10\x05\x12*\n" +
	"&SERVER_TASK_EXECUTION_STATUS_TIMED_OUT\x10\x06B$Z\"github.com/gameap/gameap/pkg/protob\x06proto3"

var (
	file_pkg_proto_servertask_proto_rawDescOnce sync.Once
	file_pkg_proto_servertask_proto_rawDescData []byte
)

func file_pkg_proto_servertask_proto_rawDescGZIP() []byte {
	file_pkg_proto_servertask_proto_rawDescOnce.Do(func() {
		file_pkg_proto_servertask_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_servertask_proto_rawDesc), len(file_pkg_proto_servertask_proto_rawDesc)))
	})
	return file_pkg_proto_servertask_proto_rawDescData
}

var file_pkg_proto_servertask_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pkg_proto_servertask_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_proto_servertask_proto_goTypes = []any{
	(ServerTaskCommand)(0),              // 0: gameap.ServerTaskCommand
	(ServerTaskOverlapPolicy)(0),        // 1: gameap.ServerTaskOverlapPolicy
	(ServerTaskCatchupPolicy)(0),        // 2: gameap.ServerTaskCatchupPolicy
	(ServerTaskExecutionStatus)(0),      // 3: gameap.ServerTaskExecutionStatus
	(*ServerTask)(nil),                  // 4: gameap.ServerTask
	(*ServerTaskSnapshot)(nil),          // 5: gameap.ServerTaskSnapshot
	(*ServerTaskDeleted)(nil),           // 6: gameap.ServerTaskDeleted
	(*ServerTaskDelta)(nil),             // 7: gameap.ServerTaskDelta
	(*ServerTaskResyncRequest)(nil),     // 8: gameap.ServerTaskResyncRequest
	(*ServerTaskExecutionStarted)(nil),  // 9: gameap.ServerTaskExecutionStarted
	(*ServerTaskExecutionFinished)(nil), // 10: gameap.ServerTaskExecutionFinished
	(*ServerTaskExecutionLog)(nil),      // 11: gameap.ServerTaskExecutionLog
	(*ServerTaskExecutionCancel)(nil),   // 12: gameap.ServerTaskExecutionCancel
	(*ServerTaskExecutionAck)(nil),      // 13: gameap.ServerTaskExecutionAck
	(*InFlightServerTaskExecution)(nil), // 14: gameap.InFlightServerTaskExecution
	(*timestamppb.Timestamp)(nil),       // 15: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),         // 16: google.protobuf.Duration
}
var file_pkg_proto_servertask_proto_depIdxs = []int32{
	0,  // 0: gameap.ServerTask.command:type_name -> gameap.ServerTaskCommand
	15, // 1: gameap.ServerTask.execute_date:type_name -> google.protobuf.Timestamp
	16, // 2: gameap.ServerTask.repeat_period:type_name -> google.protobuf.Duration
	1,  // 3: gameap.ServerTask.overlap_policy:type_name -> gameap.ServerTaskOverlapPolicy
	2,  // 4: gameap.ServerTask.catchup_policy:type_name -> gameap.ServerTaskCatchupPolicy
	15, // 5: gameap.ServerTask.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 6: gameap.ServerTaskSnapshot.tasks:type_name -> gameap.ServerTask
	15, // 7: gameap.ServerTaskSnapshot.generated_at:type_name -> google.protobuf.Timestamp
	4,  // 8: gameap.ServerTaskDelta.upserted:type_name -> gameap.ServerTask
	6,  // 9: gameap.ServerTaskDelta.deleted:type_name -> gameap.ServerTaskDeleted
	0,  // 10: gameap.ServerTaskExecutionStarted.command:type_name -> gameap.ServerTaskCommand
	15, // 11: gameap.ServerTaskExecutionStarted.started_at:type_name -> google.protobuf.Timestamp
	3,  // 12: gameap.ServerTaskExecutionFinished.status:type_name -> gameap.ServerTaskExecutionStatus
	15, // 13: gameap.ServerTaskExecutionFinished.finished_at:type_name -> google.protobuf.Timestamp
	16, // 14: gameap.ServerTaskExecutionFinished.duration:type_name -> google.protobuf.Duration
	15, // 15: gameap.InFlightServerTaskExecution.started_at:type_name -> google.protobuf.Timestamp
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pkg_proto_servertask_proto_init() }
func file_pkg_proto_servertask_proto_init() {
	if File_pkg_proto_servertask_proto != nil {
		return
	}
	file_pkg_proto_servertask_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerTaskDelta_Upserted)(nil),
		(*ServerTaskDelta_Deleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_servertask_proto_rawDesc), len(file_pkg_proto_servertask_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_servertask_proto_goTypes,
		DependencyIndexes: file_pkg_proto_servertask_proto_depIdxs,
		EnumInfos:         file_pkg_proto_servertask_proto_enumTypes,
		MessageInfos:      file_pkg_proto_servertask_proto_msgTypes,
	}.Build()
	File_pkg_proto_servertask_proto = out.File
	file_pkg_proto_servertask_proto_goTypes = nil
	file_pkg_proto_servertask_proto_depIdxs = nil
}
