//go:build wasip1

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// Patched: response buffers allocated by the host are freed after unmarshal.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v5.29.3
// source: pkg/plugin/sdk/serversettings/serversettings.proto

package serversettings

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
	_ "unsafe"
)

type serverSettingsService struct{}

func NewServerSettingsService() ServerSettingsService {
	return serverSettingsService{}
}

//go:wasmimport gameap-serversettings find_server_settings
func _find_server_settings(ptr uint32, size uint32) uint64

func (h serverSettingsService) FindServerSettings(ctx context.Context, request *FindServerSettingsRequest) (*FindServerSettingsResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _find_server_settings(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(FindServerSettingsResponse)
	err = response.UnmarshalVT(buf)
	if ptr != 0 {
		wasm.Free(ptr)
	}
	if err != nil {
		return nil, err
	}
	return response, nil
}

//go:wasmimport gameap-serversettings save_server_setting
func _save_server_setting(ptr uint32, size uint32) uint64

func (h serverSettingsService) SaveServerSetting(ctx context.Context, request *SaveServerSettingRequest) (*SaveServerSettingResponse, error) {
	buf, err := request.MarshalVT()
	if err != nil {
		return nil, err
	}
	ptr, size := wasm.ByteToPtr(buf)
	ptrSize := _save_server_setting(ptr, size)
	wasm.Free(ptr)

	ptr = uint32(ptrSize >> 32)
	size = uint32(ptrSize)
	buf = wasm.PtrToByte(ptr, size)

	response := new(SaveServerSettingResponse)
	err = response.UnmarshalVT(buf)
	if ptr != 0 {
		wasm.Free(ptr)
	}
	if err != nil {
		return nil, err
	}
	return response, nil
}
